baseURL = 'https://sinembudak.com/'
theme = 'paper'
title = "Sinem's Blog"
copyright = "© 2026. Sinem Demirkaya-Budak"
languageCode = 'en-us'
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'sinemdemirkayabudak'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'sinemdemirkayabudak'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'sinemdbudak@gmail.com'                 # gravatar email or image url
  name = 'Sinem Demirkaya-Budak'
  bio = 'Bioinformatics Engineer'

  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = false                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages

[pagination]
  pagerSize = 10

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/Sinem-DemirkayaBudak-CV.pdf"
    weight = 2
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

[taxonomies]
  tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

#   [services.disqus]
#     shortname = 'YOUR_DISQUS_SHORTNAME'     # use disqus comments

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [markup.highlight]
   lineNos = true
